abstract: A project administration tool
author: Jesse Vincent and Chia-liang Kao
distribution_type: module
generated_by: Module::Install version 0.64
license: artistic
name: CommitBit
no_index: 
  directory: 
    - inc
    - t
requires: 
  Jifty: 0.60728
  Module::CoreList: 0
  Path::Class: 0
  Text::Password::Pronounceable: 0
  UNIVERSAL::require: 0
  perl: 5.6.0
version: 0.02
